### ISSUE TITLE
DRYRUN not working in Lambda

### ISSUE THREAD

**Issue by mark-burns** [awslabs/ecr-cleanup-lambda#10]
In the Lambda environment I was unable to get the DRYRUN parameter to work. After some debugging I could see that strings were not being converted to boolean. I find that the following code works. I'm not a python expert so there may be a better way to do the same thing.

`DRYRUN = bool(str(os.environ.get('DRYRUN', "True")).lower() in ("yes", "true", "t", "1"))`

**Comment by myoung34** [comment]
I think this is resolved by #9

**Comment by mark-burns** [comment]
My review of the latest code says otherwise. When running in the Lambda environment I had to modify the code in order to get my Lambda environment variable to convert properly. Since there is no implicit cast to String I had to convert to string and compare against common values for true.

**Comment by ericdalling** [comment]
I had the same issue. The only way I could get the DRYRUN variable to evaluation as false in the lambda, was to set the DRYRUN environment variable to an empty string ("").

**Comment by anshrma** [comment]
https://github.com/awslabs/ecr-cleanup-lambda/pull/12
