### ISSUE TITLE
boto3 is not needed

### ISSUE THREAD

**Issue by Trane9991** [awslabs/ecr-cleanup-lambda#15]
Hello, 
AWS Lambda execution environment has preinstalled "boto3", so there is no need to include it in the deployment package since it makes the size of the package ~6Mb instead ~1.2Mb.

**Comment by anshrma** [comment]
Thanks for the details. However, I would prefer them to install with the package to ensure what you test is what gets delivered, and there are no surprises due to boto3 version mismatches.
