### ISSUE TITLE
Flags are not passed inside Lambda execution

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [awslabs/ecr-cleanup-lambda#3]
Following README the handler is set to `main.handler`

Lambda test:
> global name 'region' is not defined: NameError
>Traceback (most recent call last):
>File "/var/task/main.py", line 21, in handler
>if not region:
>NameError: global name 'region' is not defined

**Comment by dyroffk** [comment]
@SharpEdgeMarshall I fixed this for our purposes and pushed up a PR which should resolve the arguments not being available in Lambda
